### ISSUE TITLE
能否在4.2.0版本上集成obfs-local这个混淆插件呢？或者能否提供下4.1.7版本的插件呢？

### ISSUE THREAD

**Issue by royiie** [paldier/softcenterarm#17]
能否在4.2.0版本上集成obfs-local这个混淆插件呢？或者能否提供下4.1.7版本的插件呢？
由于在JUSTMYSOCKS上购买的节点支持obfs=tls，买的花生壳SBR-AC1900P路由器安装4.2.0版本里面没有obfs-local这个混淆插件，只有4.1.7版本上有。所以能否麻烦您稍微抽空集成或重装放出4.1.7版本，成分感谢。（shadowsocks4.1.7: https://github.com/hq450/fancyss/blob/master/fancyss_arm/Changelog.txt 这个插件不支持ARRIS1900P）

**Comment by paldier** [comment]
不做
