### ISSUE TITLE
trojan在arris3200P的arm7的系统中无法运行

### ISSUE THREAD

**Issue by zhouxiuc** [paldier/softcenterarm#19]
配置trojan节点后无法翻墙，尝试用SSH连接arris3200P路由器，手动运行trojan程序：

`admin@RT-AC3200:/jffs/softcenter/bin# ./trojan`

提示Illegal instruction，似乎是trojan的编译目标平台错误，导致无法科学上网。

**Comment by paldier** [comment]
确认，稍后更新
