### ISSUE TITLE
显示国内ok 国外fail的情况

### ISSUE THREAD

**Issue by fengurt** [paldier/softcenterarm#8]
您好

我在使用Outline提供的ss信息在asus路由器上激活使用，每次刚启动的时候可以google（虽然国外链接依然显示 fail），过一阵又不能了。。

请问这个是什么原因造成的呢 如何解决呢 

谢谢！

![image](https://user-images.githubusercontent.com/24559862/60857288-87b47980-a23c-11e9-957c-2e93d446665a.png)

**Comment by gaoben** [comment]
新版插件用httping检测国内外状态 原wget检测状态方式弃用 注意现在状态检测仍然是按需检测 只有在进入插件页面才会进行检测 退出页面后不会进行检测 鉴于网络问题 有时网站header的延迟过高 会造成有时候打X
